-- INSERT INTO Comment (userId, advertisementId, content, status)
-- VALUES
-- (11, 21, 'Bardzo polecam!', 'active'),
-- (12, 22, 'Produkt zgodny z opisem', 'active'),
-- (3, 23, 'Szybka wysyłka!', 'active'),
-- (4, 24, 'Nie polecam. Problemy z dostawą.', 'suspended'),
-- (5, 25, 'Świetny kontakt z sprzedawcą!', 'active'),
-- (6, 16, 'Towar uszkodzony', 'suspended'),
-- (7, 17, 'Super jakość!', 'active'),
-- (8, 18, 'Zbyt drogo.', 'suspended'),
-- (9, 19, 'OK', 'active'),
-- (10, 20, 'Polecam w 100%!', 'active');

-- INSERT INTO Complaint (userId, content, status)
-- VALUES
-- (11, 'Proszę o sprawdzenie płatności za ogłoszenie nr 101.', 'active'),
-- (12, 'Reklamacja dotycząca jakości ogłoszenia nr 102.', 'resolved'),
-- (3, 'Nieprawidłowe dane ogłoszenia nr 103.', 'active'),
-- (4, 'Problem z dostawą produktu z ogłoszenia nr 104.', 'active'),
-- (5, 'Brak kontaktu ze sprzedawcą z ogłoszenia nr 105.', 'resolved'),
-- (6, 'Uszkodzony towar w ogłoszeniu nr 106.', 'active'),
-- (7, 'Ogłoszenie niezgodne z opisem nr 107.', 'suspended'),
-- (8, 'Proszę o anulowanie ogłoszenia nr 108.', 'active'),
-- (9, 'Zwrot pieniędzy za ogłoszenie nr 109.', 'resolved'),
-- (10, 'Prośba o edycję ogłoszenia nr 110.', 'active');

-- INSERT INTO bumpCount (userId, commentId)
-- VALUES
-- (11, 1),
-- (12, 2),
-- (3, 2),
-- (12, 4),
-- (5, 5),
-- (6, 2),
-- (7, 7),
-- (11, 8),
-- (9, 9),
-- (12, 10);
